# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:

env:
  NODE_VERSION: 16.x
  
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
    - run: npm ci
    - run: npm test
      
    # - run: rm -rf web/build
    # - run: cd web && npm run build-ucalgary-qa
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: Staging Build
    #     path: web/build

    # - run: rm -rf web/build
    # - run: cd web && npm run build-wonderville
    # - uses: actions/upload-artifact@v1
    #   with:
    #     name: Wonderville Build
    #     path: web/build
